Add linting rules and fixes
stolostron/governance-policy-template-sync pull request #68
Opened 2021-12-02 16:08 UTC by willkutler

Signed-off-by: Will Kutler <wkutler@redhat.com>

https://github.com/open-cluster-management/backlog/issues/18036

2021-12-09 19:14 UTC, ycao56 commented
@willkutler can you rebase to make the required check pass?

2021-12-14 13:48 UTC, mprahl commented
@willkutler could you please squash those commits and ensure your single commit is signed off?

2021-12-14 13:52 UTC, mprahl requested changes

2021-12-14 13:52 UTC, mprahl commented on build/common/config/.golangci.yml
> +    - path: ^api/
Could you please remove this exception since it only applies to the policy propagator?

2021-12-14 13:52 UTC, mprahl commented on .github/workflows/kind.yml
> +        make fmt-dependencies
This was a mistake in my original PR to the propagator where I had forgotten that `make fmt` actually also calls the `fmt-dependencies` target. Could you please remove this line?

2021-12-14 13:52 UTC, mprahl commented on go.sum
> +github.com/daixiang0/gci v0.2.9 h1:iwJvwQpBZmMg31w+QQ6jsyZ54KEATn6/nfARbBNW294=
It looks like these lines were added by mistake. Could you please remove them?

2022-01-04 15:55 UTC, mprahl commented
@willkutler could you please squash your commits to a single commit?

2022-01-04 20:25 UTC, ycao56 approved these changes

2022-01-04 20:32 UTC, mprahl approved these changes

2022-01-06 18:02 UTC, willkutler commented
/retest

2022-01-06 18:43 UTC, ycao56 approved these changes

2022-01-06 19:02 UTC, mprahl approved these changes

2022-01-07 18:01 UTC, ycao56 commented
@willkutler Can you fixed the dco-signoff?

2022-01-07 20:35 UTC, dhaiducek commented
/check-dco

2022-01-07 20:36 UTC, merged